base_image: &base_image hashicorp/terraform:light
version: 2.1
workflows:
  plan:
    jobs:
      - terraform/init:
          filters:
            branches:
              only:
                - master
      - terraform/plan:
          requires:
            - terraform/init
      - approval:
          requires:
            - terraform/plan
          type: approval
      - terraform/apply:
          requires:
            - approval
